#include<iostream>
#include<vector>
#include<string>


void solve(long long N, std::string S){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::cin >> N;
    std::string S;
    std::cin >> S;
    solve(N, S);
    return 0;
}
