import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long a;
        a = sc.nextLong();
        long b;
        b = sc.nextLong();
        long c;
        c = sc.nextLong();
        solve(a, b, c);
    }

    static void solve(long a, long b, long c){
        System.out.println("This is a pen");
    }
}
