#include<iostream>
#include<vector>
#include<string>
#include<bits/stdc++.h>

using namespace std;

void solve(long long N, std::vector<long long> a){
	map<int,int> mp;
	vector<int> v;
	for(int i = 0;i < N;i++)mp[a[i]]++, v.emplace_back(a[i]);
	sort(v.begin(), v.end());
	int ans = 0;
	for(auto &&it:mp){
		if(it.first <= it.second){
			ans += it.second - it.first;
		}else{
			ans += it.second;
		}
	}
	cout<<ans<<endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::cin >> N;
    std::vector<long long> a(N);
    for(int i = 0 ; i < N ; i++){
        std::cin >> a[i];
    }
    solve(N, std::move(a));
    return 0;
}
