import java.io.*;
import java.util.*;

class Main {

	// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
	public static void main(String[] args) throws Exception {
		final Scanner sc = new Scanner(System.in);
		long N;
		N = sc.nextLong();
		String[] s = new String[(int)(N)];
		for(int i = 0 ; i < N ; i++){
			s[i] = sc.next();
		}
		long M;
		M = sc.nextLong();
		String[] t = new String[(int)(M)];
		for(int i = 0 ; i < M ; i++){
			t[i] = sc.next();
		}
		solve(N, s, M, t);
	}

	static void solve(long N, String[] s, long M, String[] t){
		int ans = 0;
		for(int i = 0;i < s.length;i++){
			int sum = 0;
			for(int j = 0;j < s.length;j++){
				if(s[i].equals(s[j]))sum++;
			}
			for(int j = 0;j < t.length;j++){
				if(s[i].equals(t[j]))sum--;
			}
			if(ans < sum)ans = sum;
		}
		System.out.println(ans);
	}
}
