#include <bits/stdc++.h>
using namespace std;


long long N;
std::vector<long long> a;

void solve(){
	map<int,int> mp;
	for(int i = 0;i < N;i++)mp[a[i]]++;
	while(mp.size() > 1){
		auto it = mp.begin();
		auto ite = mp.end();
		ite--;
		int x = it->first, X = ite->first;
		mp[X - x] += ite->second;
		mp.erase(ite);
	}
	cout<<mp.begin()->first<<endl;
}

// Generated by 1.1.7 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::cin >> N;
    a.assign(N, 0);
    for(int i = 0 ; i < N ; i++){
        std::cin >> a[i];
    }
    solve();
    return 0;
}
