#include <bits/stdc++.h>
using namespace std;


long long N;
long long K;

void solve(){

}

// Generated by 1.1.7 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::cin >> N;
    std::cin >> K;
    solve();
    return 0;
}
