#include <bits/stdc++.h>
using namespace std;

const long long MOD = 2;

void solve(long long p, std::vector<long long> a){

}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long p;
    scanf("%lld",&p);
    std::vector<long long> a(p-1-0+1);
    for(int i = 0 ; i < p-1-0+1 ; i++){
        scanf("%lld",&a[i]);
    }
    solve(p, std::move(a));
    return 0;
}
