import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long[] A = new long[(int)(3)];
        for(int i = 0 ; i < 3 ; i++){
                A[i] = sc.nextLong();
        }
        solve(A);
    }

    static void solve(long[] A){

    }
}
