[package]
name = "ahc"
version = "0.1.0"
edition = "2018"

[dependencies]
proconio = "=0.4.5"
rand = "=0.8.5"
rand_pcg = "=0.3.1"

[lib]
name = "borsh_sample"    # The name of the target.
path = "src/borsh.rs"    # The source file of the target.
