#include<bits/stdc++.h>
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";

void solve(std::string s, long long x, long long y){
	const int Base = 8005;
	bitset<Base * 2> v, h;
	v.set(Base);
	h.set(Base);
	bool start = true, horizontal = true;
	int d = 0;
	for(int i = 0;i < s.size();i++){
		if(s[i]=='F'){
			d++;
		}else{
			if(horizontal){
				if(start){
					h = (h << d);
				}else{
					h = ((h << d)|(h >> d));
				}
			}else{
				v = ((v << d)|(v >> d));
			}
			start = false;
			horizontal = not horizontal;
			d = 0;
		}
	}
	if(horizontal){
		if(start){
			h = (h << d);
		}else{
			h = ((h << d)|(h >> d));
		}
	}else{
		v = ((v << d)|(v >> d));
	}

	if(abs(x) <= Base and abs(y) <= Base and h.test(Base + x) and v.test(Base + y)){
		cout << YES << endl;
	}else{
		cout << NO << endl;
	}
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
	std::string s;
	std::cin >> s;
	long long x;
	std::cin >> x;
	long long y;
	std::cin >> y;
	solve(s, x, y);
	return 0;
}
