#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

long long N;
std::std::vector<long long> x;
std::std::vector<long long> y;

void solve(){

}

// Generated by 1.1.7 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::cin >> N;
    x.assign(N-1, 0);
    y.assign(N-1, 0);
    for(int i = 0 ; i < N-1 ; i++){
        std::cin >> x[i];
        std::cin >> y[i];
    }
    solve();
    return 0;
}
