import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[] P = new long[(int)(N-2+1)];
        for(int i = 0 ; i < N-2+1 ; i++){
            P[i] = sc.nextLong();
        }
        long Q;
        Q = sc.nextLong();
        long[] U = new long[(int)(Q)];
        long[] D = new long[(int)(Q)];
        for(int i = 0 ; i < Q ; i++){
            U[i] = sc.nextLong();
            D[i] = sc.nextLong();
        }
        solve(N, P, Q, U, D);
    }

    static void solve(long N, long[] P, long Q, long[] U, long[] D){

    }
}
