import std.algorithm;
import std.conv;
import std.stdio;
import std.string;

immutable string YES = "Yes";
immutable string NO = "No";

void solve(long N, long Q, long[] type, long[] u, long[] v){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    auto input = stdin.byLine.map!split.joiner;

    long N;
    N = input.front.to!long;
    input.popFront;

    long Q;
    Q = input.front.to!long;
    input.popFront;

    long[] type = new long[](cast(size_t) (Q));
    long[] u = new long[](cast(size_t) (Q));
    long[] v = new long[](cast(size_t) (Q));
    foreach (i; 0 .. cast(size_t) (Q)) {
        type[i] = input.front.to!long;
        input.popFront;
        u[i] = input.front.to!long;
        input.popFront;
        v[i] = input.front.to!long;
        input.popFront;
    }

    solve(N, Q, type, u, v);
    return 0;
}
