#include<iostream>
#include<vector>
#include<string>

const long long MOD = 100;

void solve(long long A, long long B, long long M){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    std::cin >> A;
    long long B;
    std::cin >> B;
    long long M;
    std::cin >> M;
    solve(A, B, M);
    return 0;
}
