#include<iostream>
#include<vector>
#include<string>

using namespace std;

void solve(long long a, long long b){
	cout<<(a + b + 1) / 2 <<endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long a;
    std::cin >> a;
    long long b;
    std::cin >> b;
    solve(a, b);
    return 0;
}
