#include<iostream>
#include<vector>
#include<string>


void solve(long long R, long long B, long long x, long long y){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long R;
    std::cin >> R;
    long long B;
    std::cin >> B;
    long long x;
    std::cin >> x;
    long long y;
    std::cin >> y;
    solve(R, B, x, y);
    return 0;
}
