#include <bits/stdc++.h>
using namespace std;


long long N;
std::std::vector<long long> H;
std::std::vector<long long> P;

void solve(){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::cin >> N;
    H.assign(N, 0);
    P.assign(N, 0);
    for(int i = 0 ; i < N ; i++){
        std::cin >> H[i];
        std::cin >> P[i];
    }
    solve();
    return 0;
}
