#include<iostream>
#include<vector>
#include<string>
#include<algorithm>

using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";

void solve(std::string s, std::string t){
	sort(s.begin(), s.end());
	sort(t.begin(), t.end());
	reverse(t.begin(), t.end());
	if(s < t){
		cout<<YES<<endl;
	}else{
		cout<<NO<<endl;
	}
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string s;
    std::cin >> s;
    std::string t;
    std::cin >> t;
    solve(s, t);
    return 0;
}
