#include<iostream>
#include<vector>
#include<string>

const std::string YES = "Yes";
const std::string NO = "No";

void solve(std::string C, std::string c){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string C;
    std::cin >> C;
    std::string c;
    std::cin >> c;
    solve(C, c);
    return 0;
}
