#include <bits/stdc++.h>
using namespace std;


long long N;
long long x;
std::std::vector<long long> a;

void solve(){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::cin >> N;
    std::cin >> x;
    a.assign(N, 0);
    for(int i = 0 ; i < N ; i++){
        std::cin >> a[i];
    }
    solve();
    return 0;
}
